# Generated by Django 3.0.3 on 2020-02-19 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 19, 3, 56, 51, 153411, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='not marked', max_length=50),
        ),
    ]
